### ISSUE TITLE
Arguments do not work

### ISSUE THREAD

**Issue by miheerdew** [sameer-b/AutoHathwayLogin#2]
The setup function does not update the global constants. Also the url must be updated after the setup is done.

**Comment by sameer-b** [comment]
Could you post a failed test case?

**Comment by miheerdew** [comment]
The timeout of 30s keeps on being used, even if I supply any other argument.

**Comment by sameer-b** [comment]
Can you post a generated url and command you used to invoke the script?

**Comment by miheerdew** [comment]
$> python AutoHathwayLogin.py username pass 10
Internet connectivity alive. Sleeping for 30 seconds.
Internet connectivity alive. Sleeping for 30 seconds.
.
.
