### ISSUE TITLE
Issue with connectivity detection

### ISSUE THREAD

**Issue by miheerdew** [sameer-b/AutoHathwayLogin#5]
I was unable to connect to the internet ( www.google.com would redirect me to the hathway site), however the script showed `Internet connectivity alive` message. Is it because redirection does not raise an exception?

**Comment by sameer-b** [comment]
I did not think of this. I guess Hathway has changed the way they redirect. Does behavior change with naked urls? I mean https://google.com and https://www.google.com are treated differently.

**Comment by miheerdew** [comment]
http://www.google.com and http://74.125.130.103 (google's ip) are redirected. However, https://www.google.com isn't. Any other http request is redirected.

**Comment by sameer-b** [comment]
You are correct. Last pull request broke this code completely. What do you think we should do? Check http status code?

**Comment by miheerdew** [comment]
Checking the status code may not help, because www.google.com itself sends a content moved code to www.google.co.in.
I suggest changing http to https. And to make it even foolproof, we could also check the certificate.

**Comment by sameer-b** [comment]
its only time untill Hathway does redirect on https as well.

**Comment by miheerdew** [comment]
It can't right, because browsers will show a server idenetity cannot be identified message.

**Comment by sameer-b** [comment]
changed it to https://www.google.com. I'm not on a Hathway line anymore. Could you test it?

**Comment by miheerdew** [comment]
No this is not what I meant. I meant we should make a https connection to google and verify if that connection is made properly ( by checking the certificate ). Only then should we say that internet is connected, otherwise not. I guess that this should not make any difference. Will check it anyway.

**Comment by sameer-b** [comment]
Does it work? Should I merge with master?

**Comment by miheerdew** [comment]
I did not get time to check it properly. The issue was that the timeout did not work ( or maybe it did and I did not wait that long ).So, I tried to kill the program with CTRL+C, however the KeyboardInterrupt was caught in the except block, which made the program log me in.

I am no longer on the hathway network. So can't test any further. However at least it did not falsely detect as connected to the Internet

**Comment by rickysarraf** [comment]
On Saturday 04 October 2014 08:58 AM, Sameer Balasubrahmanyam wrote:

> I did not think of this. I guess Hathway has changed the way they 
> redirect. Does behavior change with naked urls? I mean 
> https://google.com and https://www.google.com are treated differently. 

I'm still using the old whatever I was using and it still works. Just FYI.

## 

Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by sameer-b** [comment]
ricky are you on Hathway? Can you test the current master?

**Comment by sameer-b** [comment]
I'm closing this issue. Current branch seems to be working. Let me know if there are more bugs.

**Comment by ghost** [comment]
this issue persists, the script is not able to detect redirection

**Comment by rickysarraf** [comment]
@raghukamath Can you provide steps on how you concluded that ? I'm still on the same codebase, and it works.

**Comment by ghost** [comment]
I ran the script and it didn't log me in. All the pages where redirected . But the log file showed the Internet connectivity alive message. I even tried purposely logging out of hathway but the terminal output as well as the log file showed same message. 

Please tell me which hathway plan do you have and how it works. Thanks in advance for your help

**Comment by rickysarraf** [comment]
On Wednesday 01 April 2015 06:41 PM, raghukamath wrote:

> I ran the script and it didn't log me in. All the pages where
> redirected . But the log file showed the Internet connectivity alive
> message. I even tried purposely loging out of hathway but the terminal
> output as well as the log file showed same message.
> 
> Please tell me which hathway plan do you have and how it works. Thanks
> in advance for your help

Can you be specific here?

Redirection in the web browser or redirection for the python url ?

Looking at the code:

```
                    try:
                            local_write("%s\tTrying to authenticate
```

to server %s\n" % (time.ctime(), real_host) )
                                urllib2.urlopen(real_host)
                        except:
                                local_write("%s\tFailed to connect to %s
Retrying\n" % (time.ctime(), real_host) )
                                continue

While I'm not happy that we chose a catchall exception, but if you are
getting a false positive, the error must be somewhere else.

Assuming what you said is correct, and we are getting a redirection,  we
definitely would have gotten an exception, which would have been caught
and an error msg logged.

```
urlopen(url, data=None) -- Basic usage is the same as original
urllib.  pass the url and optionally data to post to an HTTP URL, and
get a file-like object back.  One difference is that you can also pass
a Request instance instead of URL.  Raises a URLError (subclass of
IOError); for HTTP errors, raises an HTTPError, which can also be
treated as a valid response.
```

## 

Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by rickysarraf** [comment]
On Wednesday 01 April 2015 06:41 PM, raghukamath wrote:

> I ran the script and it didn't log me in. All the pages where
> redirected . But the log file showed the Internet connectivity alive
> message. I even tried purposely loging out of hathway but the terminal
> output as well as the log file showed same message.
> 
> Please tell me which hathway plan do you have and how it works. Thanks
> in advance for your help

Can you be specific here?

Redirection in the web browser or redirection for the python url ?

Looking at the code:

```
                    try:
                            local_write("%s\tTrying to authenticate
```

to server %s\n" % (time.ctime(), real_host) )
                                urllib2.urlopen(real_host)
                        except:
                                local_write("%s\tFailed to connect to %s
Retrying\n" % (time.ctime(), real_host) )
                                continue

While I'm not happy that we chose a catchall exception, but if you are
getting a false positive, the error must be somewhere else.

Assuming what you said is correct, and we are getting a redirection,  we
definitely would have gotten an exception, which would have been caught
and an error msg logged.

```
urlopen(url, data=None) -- Basic usage is the same as original
urllib.  pass the url and optionally data to post to an HTTP URL, and
get a file-like object back.  One difference is that you can also pass
a Request instance instead of URL.  Raises a URLError (subclass of
IOError); for HTTP errors, raises an HTTPError, which can also be
treated as a valid response.
```

## 

Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by ghost** [comment]
Ok to be specific when I run the script in terminal by using the given command in the read-me file it gives me this message "Internet connectivity alive. Sleeping for 30 sec" , while my browser redirects to a page which is normally shown when we are logged out.

for e.g. when I go to a reddit page (http://www.reddit.com/r/linux)
I get redirected to 404 page, the content of the page is below : 

---

HTTP Status 404 - /r/linux

type Status report

message /r/linux

description The requested resource (/r/linux) is not available.

JBossWeb/2.0.1.GA.

---

I even tried purposely logging out and testing the script even when i am logged out of hathway it says internet is alive . 

I setup a cron and the log file( generated by the script in /tmp/hathway.log ) too had same message.

Should i give you a link to video of demonstrating this?

**Comment by rickysarraf** [comment]
Ummm.. One of us has to look at the code again. This is a good reason to
have extended logging

s3nt fr0m a $martph0ne, excuse typ0s

**Comment by rickysarraf** [comment]
BTW, a 404 error means the URL is invalid.

s3nt fr0m a $martph0ne, excuse typ0s

**Comment by ghost** [comment]
Are you on hathway

**Comment by rickysarraf** [comment]
Yes. I am.

s3nt fr0m a $martph0ne, excuse typ0s
